name: mlflow-env
run: |
  cd MLProject
  mlflow run .
channels:
  - conda-forge

dependencies:
  - python=3.10
  - pip
  - pip:
      - mlflow==2.19.0
      - pandas
      - numpy
      - scikit-learn==1.7.2