name: CI MLflow

on:
  push:
    branches:
      - main

jobs:
  run-mlflow:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-activate-base: true
          python-version: "3.10"
          activate-environment: base

      - name: Install dependencies
        shell: bash -l {0}
        run: |
          pip install mlflow

      - name: Run MLflow Project
        shell: bash -l {0}
        run: |
          cd MLProject
          mlflow run .